### ISSUE TITLE
Catalog - remove inApp native bars

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#92]
Remove native bars from the native side and use Cobalt nativeBars feature in the whole app.

- [x] web : remove setTexts and use bars method
- [x] add a default bars configuration to cobalt.conf
- [x] remove bars on iOS (except for callback/events pages)
- [x] remove setTexts on iOS
- [x] remove bars on Android (except for callback/events pages)
- [x] remove theme on Android (use default Cobalt.Light one without customization)
- [x] remove setTexts on Android
- [x]  check everything looks fine
- [x] merge on develop
- [x] @ggendre Write an issue about handling default bars configuration in `cobalt.conf`

**Comment by ggendre** [comment]
done for the web side. created `issue-92` branches on catalog for native parts. assign it back to me when it's done

**Comment by Doc1faux** [comment]
Clean Theme for Android apps.
Everything is fine on develop branches.
But for Catalog, `issue-92` branches are still existing... @ggendre merge or remove them?

**Comment by ggendre** [comment]
The idea of this issue was to propose a Catalog app that was using a maximum of cobalt features. So that people know they can easily have the same app with too much headhaches. I'm not totally against the fact that some theming is done on the native side. But we need to document this if we do so. And what about iOS? There is no theming on iOS...

Maybe we can mix both solutions : having the cobalt bars for almost all pages and a special one, plugins for example, themed on native side ?
I think we should use `issue-92` as a basis and re-apply some of your theme changes on top of it.

**Comment by Doc1faux** [comment]
You said it yourself: "people know they can easily have the same app with too much headaches" :P 
Without joking, I don't think that's a good idea for the moment to show users that if they want a default theme on Android, they have to define it for each "controller" in `cobalt.conf`...

I subscribe to your point about the documentation ;)

On iOS, there is no theming definition like on Android.
But like it, you can define one (but in code) only once for the whole app with the UIAppearance class on the application ([to investigate](https://www.raywenderlich.com/108766/uiappearance-tutorial)).

I would propose the totally opposite ;) 
Use native for the default Theme use everywhere in the app except in Dark, NativeBars & Plugins where it is done by the Web.

I have already planned this morning to merge develop in `issue-92` to test if Default Themed Value feature/fixes changes has no impact on this.

**Comment by Doc1faux** [comment]
Move default bars configuration from `cobalt.conf` to native because, for the moment, it needs to be defined for each controller.
@ggendre Write an issue about this?

**Comment by ggendre** [comment]
Issue created : [cobalt.conf] better default configuration #129
Closing
